import { BenefitCategory } from "../types/benefit.types";

export const SIMPLE_CATEGORY_KEYWORDS: Record<BenefitCategory, string[]> = {
  programas_puntos: [
    "puntos",
    "puntos extra",
    "millas",
    "latam pass",
    "sky plus",
    "dolares premio",
    "dolares-premio",
    "recompensas",
    "recompensa",
  ],
  donaciones: [
    "donacion",
    "donaciones",
    "fundacion",
    "fundacion nuestros hijos",
    "dkms",
    "reforestemos",
    "corporacion",
    "aporte",
    "hazte socio",
  ],
  seguros: [
    "seguro",
    "seguros",
    "seguro de auto",
    "seguro de vida",
    "seguro de viajes",
    "seguro de cesantia",
    "seguro rci",
    "asistencia en viaje",
  ],
  estacionamientos: [
    "estacionamiento",
    "estacionamientos",
    "parking",
    "mcparking",
    "airport parking",
  ],
  combustible: [
    "combustible",
    "bencina",
    "copec",
    "shell",
    "lipigas",
    "gasco",
    "parafina",
    "gas licuado",
  ],
  movilidad: [
    "metro",
    "tren",
    "tren nos",
    "limache-puerto",
    "movilidad",
    "transporte",
    "e-mobility",
    "scooter",
    "bicicleta",
    "bicicletas",
    "moto electrica",
    "moto electrico",
  ],
  viajes: [
    "viajes",
    "travel",
    "hotel",
    "hoteles",
    "vuelo",
    "vuelos",
    "turismo",
    "booking",
    "despegar",
    "aerolinea",
    "aeropuerto",
    "escapadas",
    "resort",
    "lounge",
    "salones vip",
    "pacific club",
    "primeclass",
  ],
  automotriz: [
    "automotriz",
    "automotor",
    "auto",
    "autos",
    "vehiculo",
    "vehiculos",
    "taller",
    "neumaticos",
    "repuestos",
    "rent a car",
  ],
  salud: [
    "farmacia",
    "cruz verde",
    "salcobrand",
    "ahumada",
    "clinica",
    "salud",
    "optica",
    "laboratorio",
    "dental",
    "medico",
    "medicina",
  ],
  belleza: [
    "belleza",
    "peluqueria",
    "barber",
    "spa",
    "cosmetica",
    "maquillaje",
    "perfumeria",
    "skincare",
  ],
  deportes_bienestar: [
    "deportes",
    "deporte",
    "deportivo",
    "gimnasio",
    "gym",
    "fitness",
    "running",
    "padel",
    "wellness",
    "bienestar",
    "yoga",
    "pilates",
    "mall sport",
  ],
  educacion: [
    "educacion",
    "colegio",
    "universidad",
    "instituto",
    "curso",
    "cursos",
    "libreria",
    "librerias",
    "libros",
    "clases",
    "english",
    "preuniversitario",
  ],
  mascotas: ["mascota", "mascotas", "pet", "veterinaria", "veterinario"],
  tecnologia: [
    "tecnologia",
    "tecnologia y marketplace",
    "celular",
    "notebook",
    "smartphone",
    "electro",
    "electrohogar",
    "gaming",
    "apple",
    "samsung",
    "smarthome",
  ],
  hogar: [
    "hogar",
    "muebles",
    "decoracion",
    "colchon",
    "cocina",
    "dormitorio",
    "menaje",
    "casa",
    "climatizacion",
    "temperado de agua",
    "calefaccion",
  ],
  moda: [
    "moda",
    "moda y vestuario",
    "vestuario",
    "vestuario y calzado",
    "calzado",
    "zapatos",
    "zapatillas",
    "adidas",
    "asics",
    "h&m",
    "zara",
    "guess",
    "pandora",
  ],
  retail: [
    "retail",
    "marketplace",
    "falabella",
    "paris",
    "ripley",
    "tienda departamental",
    "catalogo productos",
  ],
  supermercados: [
    "supermercado",
    "supermercados",
    "jumbo",
    "santa isabel",
    "lider",
    "unimarc",
    "tottus",
    "spid",
  ],
  delivery: [
    "delivery",
    "despacho",
    "pedidos ya",
    "pedidosya",
    "ubereats",
    "uber eats",
    "rappi",
  ],
  comida_rapida: [
    "comida rapida",
    "fast food",
    "pizza",
    "burger",
    "papas fritas",
    "hot dog",
    "kfc",
    "doggis",
    "mcdonald",
    "papa john",
    "domino",
    "subway",
    "mostaza",
    "hamburguesa",
  ],
  cafeterias: [
    "cafeterias",
    "cafeteria",
    "cafe",
    "coffee",
    "starbucks",
    "juan valdez",
    "dunkin",
    "pasteleria",
    "heladeria",
    "chocolat",
    "gelato",
  ],
  restaurantes: [
    "restaurantes y bares",
    "restaurantes",
    "restaurant",
    "restaurante",
    "bar",
    "bistro",
    "gourmet",
    "sabores",
    "sabores gourmet",
    "antojos",
    "sushi",
    "nikkei",
    "trattoria",
    "brasa",
    "grill",
  ],
  entretencion: [
    "entretencion",
    "panoramas",
    "panorama",
    "cine",
    "teatro",
    "festival",
    "concierto",
    "show",
    "musica",
    "ticketera",
    "ticketera",
    "evento",
    "eventos",
    "zoologico",
    "parque",
    "disney",
    "hasbro",
    "leyendas",
  ],
  servicios: [
    "servicios",
    "billetera digital",
    "autorizador",
    "contribuciones",
    "cuentas",
    "pagos",
  ],
  sustentabilidad: [
    "sustentable",
    "sustentabilidad",
    "solar",
    "paneles solares",
    "ecologico",
    "ecologica",
    "reforestacion",
    "bosques",
    "energia solar",
    "movilidad electrica",
  ],
  otros: [],
};
